import type { Metadata } from 'next';
import '@/styles/global.css';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Impact Web Shop',
  description: 'Generated by create next app',
  openGraph: {
    type: 'website',
    locale: 'en_US',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
