import type { Metadata } from 'next';
import '@/styles/global.css';
import { ReactNode } from 'react';
import Header from '@/app/(unauth)/components/header/Header';
import Footer from '@/app/(unauth)/components/footer/Footer';
import { CartProvider } from '../context/CartContext';

export const metadata: Metadata = {
  title: 'Impact Web Shop',
  description: 'Generated by create next app',
  openGraph: {
    type: 'website',
    locale: 'en_US',
  },
};

import { Roboto } from 'next/font/google';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html className={roboto.className} lang="en">
      <body>
        <CartProvider>
          <Header/>
            {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
